export const RPC = {
  HASH: 'HASH',
  LOGIN: 'LOGIN',
  EMAIL: 'EMAIL',
  USER: 'USER',
  UPDATE: 'UDPDATE',
  SEND_EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PRECONTRACT: 'PRECONTRACT',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  SMS: 'SMS',
  NOTIFICATION: 'PUSH_NOTIFICATION',
  SEND_VERIFICATION: 'SEND_VERIFICATION',
  VERIFY: 'VERIFY',
  EMAILRECOVERYPASSWORD: 'RECOVERYPASSWORD',
  UPDATEUSERTRANSACTION: 'BUY_SELL_UPDATE_USER',
  GETUSERARRAY: 'GET_USERS_BY_ARRAY',
};

export const STATUS = {
  UNAUTH: 'UNAUTH',
  AUTH: 'AUTH',
};

export const CODES = {
  SIGN_IN: 'AS2001',
  SIGN_IN_ERROR: 'AS4001',
  SIGN_UP: 'AS2002',
  SIGN_UP_ERROR: 'AS4002',
};

export enum PROVIDER {
  EMAIL = 'EMAIL',
  FACEBOOK = 'FACEBOOK',
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
}
export const NOTIFICATIONSSUBJECT = {
  CHANGEPASSWORD: 'Solicitud cambio de contraseña',
  ACTIVATEUSER: 'Bienvenido a Techify',
};

export enum TYPECATEGORY {
  ALL = 'ALL',
  SELLER = 'SELLER',
  TECHIFY = 'TECHIFY',
}

export enum TYPEPRODUCT {
  TECHIFY_VERIFIED = 'VERIFICADO TECHIFY',
  ESSENTIALS = 'ESSENTIALS',
  REGULAR = 'REGULAR',
}

export enum STATUSPRODUCT {
  ACTIVE = 'ACTIVE',
  BOOKED = 'BOOKED',
  SOLD = 'SOLD',
}

export enum STATEPRODUCT {
  PRECINTADO = 'PRECINTADO',
  NUEVO = 'NUEVO',
  VERY_GOOO = 'MUY BUENO',
  GOOO = 'BUENO',
  ACEPTABLE = 'ACEPTABLE',
}
export enum USERTYPEWALLET {
  NATURAL = 'NATURAL',
  PAYER = 'PAYER',
}

export enum USERTYPE {
  SELLER = 'SELLER',
  BUYER = 'BUYER',
}
